/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_annteng_myapplicationonmac_DisplayMessageActivity */

#ifndef _Included_com_example_annteng_myapplicationonmac_DisplayMessageActivity
#define _Included_com_example_annteng_myapplicationonmac_DisplayMessageActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_annteng_myapplicationonmac_DisplayMessageActivity
 * Method:    helloString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_annteng_myapplicationonmac_DisplayMessageActivity_helloString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
